services:
  localstack:
    image: localstack/localstack:3.0.0
    container_name: localstack

    ports:
      - '4566:4566'

    environment:
      - SERVICES=s3,ses
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
      - LOCALSTACK_AUTH_TOKEN=

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack-data:/var/lib/localstack

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant

    ports:
      - '6333:6333' # REST API
      - '6334:6334' # gRPC (optional)

    volumes:
      - ./qdrant-data:/qdrant/storage

    restart: unless-stopped
