export const API_VERSION = 'v1';
export const JWT_ACCESS_TOKEN_EXPIRATION = '1d';
export const JWT_REFRESH_TOKEN_EXPIRATION = '7d';
export const JWT_REFRESH_TOKEN_EXPIRATION_REMEMBER_ME = '30d';
export const JWT_FORGET_PASSWORD_EXPIRATION = '15m';
export const JWT_EMAIL_VERIFICATION_EXPIRATION = '1d';
